Доработки по условиям 9 спринта
wrinfotel/java-kanban pull request #4
Opened 2024-12-10 15:17 UTC by wrinfotel

- добавлен http сервер
- добавлены эндпоинты для работы с методами TaskManager
- добавлены тесты на эндпоинты и работу сервера

2024-12-11 11:13 UTC, ErkinKasymaliev reviewed
привет, оставил комменты

2024-12-11 11:13 UTC, ErkinKasymaliev commented on src/http/handlers/BaseHttpHandler.java
> +    protected void sendSuccessChaged(HttpExchange h, String text) throws IOException {
sendCreated

2024-12-11 11:13 UTC, ErkinKasymaliev commented on src/http/handlers/BaseHttpHandler.java
> +public class BaseHttpHandler {
создайте private method 
`private void baseResponse (HttpExchange  h, String text, int code, boolean hasBody) throws IOException;
`остальные методы у вас будут выглядеть так:
```
protected void sendText(HttpExchange h, String text) throws IOException {
   this.baseResponse(h, text, 200, true);
}
```

а то у вас все повторяется

2024-12-11 11:13 UTC, ErkinKasymaliev commented on src/http/handlers/EpicHandler.java
> +        GsonBuilder gsonBuilder = new GsonBuilder();
давайте это уберем из всех handler в BaseHttpHandler: там создадим поле protected GsonBuilder gsonBuilder = new GsonBuilder(); 
а это в конструктор:
gsonBuilder.registerTypeAdapter(Duration.class, new DurationAdapter());
gsonBuilder.registerTypeAdapter(LocalDateTime.class, new LocalDateTimeAdapter());
Gson gson = gsonBuilder.create();

2024-12-11 11:13 UTC, ErkinKasymaliev commented on src/http/handlers/EpicHandler.java
> +                try (InputStream inputStream = exchange.getRequestBody()) {
давайте все внутри case уберем в private метод с названием-глаголами:
```
case "POST":
   handlePost(сигнатура);
   break;
case "GET":
   handleGet();
   break;
....
```

2024-12-11 11:13 UTC, ErkinKasymaliev commented on src/http/handlers/EpicHandler.java
> +                try (InputStream inputStream = exchange.getRequestBody()) {
аналогичные комменты для TaksHandler и SubtaskHandler

2024-12-11 11:13 UTC, ErkinKasymaliev commented on src/taskmanager/InMemoryTaskManager.java
> +            if (subtask != null) {
```
if (subtask == null) {
  throw new NotFoundException("Subtask not found");
}
Optional<Duration> subtaskDuration = Optional.ofNullable(subtask.getDuration());
...
```

2024-12-11 17:13 UTC, ErkinKasymaliev requested changes
еще один коммент

2024-12-11 17:13 UTC, ErkinKasymaliev commented on src/http/handlers/EpicHandler.java
> +        gsonBuilder.registerTypeAdapter(Duration.class, new DurationAdapter());
зачем?) удалите это отсюда и private final Gson gson;
создайте конструктор в BaseHttpHandler


```
class BaseHttpHandler {
   protected Gson gson;

   BaseHttpHandler() {
     gsonBuilder.registerTypeAdapter(Duration.class, new DurationAdapter());
     gsonBuilder.registerTypeAdapter(LocalDateTime.class, new LocalDateTimeAdapter());
     gson = gsonBuilder.create();
   }
```

в конструкторах наследниках `super();`

```
public EpicHandler(TaskManager taskManager) {
        super();
        this.taskManager = taskManager;
}
```

2024-12-11 18:50 UTC, wrinfotel commented on src/http/handlers/EpicHandler.java
> +        gsonBuilder.registerTypeAdapter(Duration.class, new DurationAdapter());
я специально не стал так делать, на случай если в дальнейшем нужны будут дополнительные адаптеры для каких то полей или не нужны будут уже заданные

2024-12-12 06:17 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-12-12 07:10 UTC, merged